name: "Unit Tests"
description: "Run unit tests using go"
env:
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"
runs:
  using: "composite"
  steps:
    - name: Check out code.
      uses: actions/checkout@v3.2.0
    - name: Install Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version-file: "go.mod"
    - name: Test
      shell: bash
      run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
