dynatraceService:
  image:
    repository: docker.io/keptncontrib/dynatrace-service # Container Image Name
    pullPolicy: IfNotPresent                 # Kubernetes Image Pull Policy
    tag: ""                                  # Container Tag
  service:
    enabled: true                            # Creates a Kubernetes Service for the dynatrace-service
  config:
    generateTaggingRules: false              # Generate Tagging Rules in Dynatrace Tenant
    generateProblemNotifications: false      # Generate Problem Notifications in Dynatrace Tenant
    generateManagementZones: false           # Generate Management Zones in Dynatrace Tenant
    generateDashboards: false                # Generate Dashboards in Dynatrace Tenant
    generateMetricEvents: false              # Generate Metric Events in Dynatrace Tenant
    synchronizeDynatraceServices: true       # Synchronize Service Entities between Dynatrace and Keptn
    synchronizeDynatraceServicesIntervalSeconds: 60       # Synchronization Interval
    httpSSLVerify: true                      # Verify HTTPS SSL certificates
    httpProxy: ""                            # Proxy for HTTP requests
    httpsProxy: ""                           # Proxy for HTTPS requests
    noProxy: "127.0.0.1,mongodb-datastore,configuration-service,shipyard-controller"      # Proxy exceptions for HTTP and HTTPS requests
    logLevel: "info"                         # Minimum log level to log
    keptnApiUrl: ""                          # URL of keptn API
    keptnBridgeUrl: ""                       # URL of keptn bridge

distributor:
  metadata:
    hostname: ""                             # Sets the hostname sent by the distributor to the control-plane
    namespace: ""                            # Sets the namespace sent by the distributor to the control-plane
  stageFilter: ""                            # Sets the stage this dynatrace-service belongs to
  serviceFilter: ""                          # Sets the service this dynatrace-service belongs to
  projectFilter: ""                          # Sets the project this dynatrace-service belongs to
  image:
    repository: docker.io/keptn/distributor  # Container Image Name
    pullPolicy: IfNotPresent                 # Kubernetes Image Pull Policy
    tag: "0.8.7"                             # Container Tag

remoteControlPlane:
  enabled: false                             # Enables remote execution plane mode
  api:
    protocol: "https"                        # Used Protocol (http, https)
    hostname: ""                             # Hostname of the control plane cluster (and Port)
    apiValidateTls: true                     # Defines if the control plane certificate should be validated
    token: ""                                # Keptn API Token

imagePullSecrets: []                         # Secrets to use for container registry credentials

serviceAccount:
  create: true                               # Enables the service account creation
  annotations: {}                            # Annotations to add to the service account
  name: ""                                   # The name of the service account to use.

podAnnotations: {}                           # Annotations to add to the created pods

podSecurityContext:                          # Set the pod security context (e.g. fsGroups)
   fsGroup: 65532

securityContext:                             # Set the security context (e.g. runAsUser)
  runAsNonRoot: true
  runAsUser: 65532
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

resources: {}                                 # Resource limits and requests
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}                                # Node selector configuration

tolerations: []                                 # Tolerations for the pods

affinity: {}                                    # Affinity rules
