dynatraceService:
  image:
    repository: docker.io/keptncontrib/dynatrace-service # Container Image Name
    pullPolicy: IfNotPresent                 # Kubernetes Image Pull Policy
    tag: ""                                  # Container Tag
  service:
    enabled: true                            # Creates a Kubernetes Service for the dynatrace-service
  config:
    generateTaggingRules: false              # Generate Tagging Rules in Dynatrace Tenant
    generateProblemNotifications: false      # Generate Problem Notifications in Dynatrace Tenant
    generateManagementZones: false           # Generate Management Zones in Dynatrace Tenant
    generateDashboards: false                # Generate Dashboards in Dynatrace Tenant
    generateMetricEvents: false              # Generate Metric Events in Dynatrace Tenant
    synchronizeDynatraceServices: true       # Synchronize Service Entities between Dynatrace and Keptn
    synchronizeDynatraceServicesIntervalSeconds: 60       # Synchronization Interval
    httpSSLVerify: true                      # Verify HTTPS SSL certificates
    httpProxy: ""                            # Proxy for HTTP requests
    httpsProxy: ""                           # Proxy for HTTPS requests
    noProxy: ""                              # Proxy exceptions for HTTP and HTTPS requests
    logLevel: "info"                         # Minimum log level to log
    keptnApiUrl: ""                          # URL of keptn API
    keptnBridgeUrl: ""                       # URL of keptn bridge

imagePullSecrets: []                         # Secrets to use for container registry credentials

serviceAccount:
  create: true                               # Enables the service account creation
  annotations: {}                            # Annotations to add to the service account

podAnnotations: {}                           # Annotations to add to the created pods

podSecurityContext:                          # Set the pod security context (e.g. fsGroups)
   fsGroup: 65532

securityContext:                             # Set the security context (e.g. runAsUser)
  runAsNonRoot: true
  runAsUser: 65532
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  seccompProfile:
      type: RuntimeDefault

distributor:
  metadata:
    hostname: ""                             # Sets the hostname sent by the distributor to the control-plane
    namespace: ""                            # Sets the namespace sent by the distributor to the control-plane

resources:                                  # Set resources limits and requests
  limits:
    cpu: 128m
    memory: 200Mi
  requests:
    cpu: 32m
    memory: 50Mi

nodeSelector: {}                                # Node selector configuration

tolerations: []                                 # Tolerations for the pods

affinity: {}                                    # Affinity rules

terminationGracePeriodSeconds: 30               # Pod termination grace period in seconds
workGracePeriodSeconds: 20                      # Seconds allocated to completing work in the event of a graceful shutdown
replyGracePeriodSeconds: 5                      # Seconds allocated to replying in the event of a graceful shutdown
