runner:
  gofmt:
    cmd: gofmt -l .
    errorformat:
      - "%f:%l:%c: %m"
  golangci-lint:
    cmd: golangci-lint run -E bodyclose,exportloopref,funlen,gocyclo,gosec,nestif,unparam --out-format=line-number --timeout=10m ./...
    errorformat:
      - "%f:%l:%c: %m"
