apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: keptncontrib/dynatrace-service
      docker:    # 	beta describes an artifact built from a Dockerfile.
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: dynatrace-service # needs to be the same name as currently used (check via helm ls -n keptn)
        namespace: keptn # needs to be the same namespace as where the helm-chart is currently deployed
        artifactOverrides:
          image: keptncontrib/dynatrace-service
        overrides:
          securityContext:
            readOnlyRootFilesystem: false
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          distributor:
            metadata:
              namespace: keptn
        chartPath: chart
