# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
# Configure Monitoring
POST http://localhost:8081/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/cloudevents+json

{
  "contenttype": "application/json",
  "data": {
    "type": "dynatrace",
    "project": "sockshop"
  },
  "id": "b3c3c357-eb3d-4f90-b26e-9ebfedfb8dbf",
  "source": "cli",
  "specversion": "0.2",
  "time": "2019-10-14T08:00:09.416Z",
  "type": "sh.keptn.event.monitoring.configure",
  "shkeptncontext": "71270488-b923-400a-8ac5-7f471b15a181"
}

###
POST http://localhost:8081/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/cloudevents+json

{
  "contenttype": "application/json",
  "data": {
    "eventContext": {
      "keptnContext": "748250f9-b474-4432-8767-f78600e2d5a3",
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDY1NzEyNTF9.xEeMWkSzMsCh9l4Y2GZi_HOy-wD5Z54aV8vrNiwnyug"
    },
    "project": "sockshop",
    "shipyard": "c3RhZ2VzOg0KICAtIG5hbWU6ICJkZXYiDQogICAgZGVwbG95bWVudF9zdHJhdGVneTogImRpcmVjdCINCiAgICB0ZXN0X3N0cmF0ZWd5OiAiZnVuY3Rpb25hbCINCiAgLSBuYW1lOiAic3RhZ2luZyINCiAgICBkZXBsb3ltZW50X3N0cmF0ZWd5OiAiYmx1ZV9ncmVlbl9zZXJ2aWNlIg0KICAgIHRlc3Rfc3RyYXRlZ3k6ICJwZXJmb3JtYW5jZSINCiAgLSBuYW1lOiAicHJvZHVjdGlvbiINCiAgICBkZXBsb3ltZW50X3N0cmF0ZWd5OiAiYmx1ZV9ncmVlbl9zZXJ2aWNlIg0KICAgIHJlbWVkaWF0aW9uX3N0cmF0ZWd5OiAiYXV0b21hdGVkIg0K"
  },
  "id": "78ad03bc-f3a2-4b31-9560-e127f2f36dd2",
  "source": "https://github.com/keptn/keptn/api",
  "specversion": "0.2",
  "time": "2019-12-04T13:47:31.025Z",
  "type": "sh.keptn.internal.event.project.create",
  "shkeptncontext": "748250f9-b474-4432-8767-f78600e2d5a3"
}

###




