# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/cloudevents+json

{
  "type": "sh.keptn.internal.event.get-sli",
  "contenttype": "application/json",
  "specversion": "0.2",
  "source": "test-event",
  "data": {
    "customFilters": [
    ],
    "deploymentstrategy": "direct",
    "start": "2020-07-09T12:28:14Z",
    "end": "2020-07-09T14:28:53Z",
    "indicators": [
      "response_time_p95",
      "response_time_p90",
      "response_time_p50",
      "error_rate",
      "throughput"
    ],
    "project": "dynatrace",
    "service": "sampleservice",
    "sliProvider": "dynatrace",
    "stage": "qualitystage",
    "teststrategy": "performance",
    "labels": {
      "testid": "12345",
      "buildnr": "build17",
      "runby": "JohnDoe",
      "dttag" : "evalservice"
    }
  }
}
###
