---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-dynatrace-service
  labels:
    "app": "keptn"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-dynatrace-service-secrets
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-dynatrace-service-secrets
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-dynatrace-service-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-dynatrace-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-service
spec:
  selector:
    matchLabels:
      run: dynatrace-service
  replicas: 1
  template:
    metadata:
      labels:
        run: dynatrace-service
    spec:
      securityContext:
        fsGroup: 65532
      serviceAccountName: keptn-dynatrace-service
      containers:
        - name: dynatrace-service
          image: keptncontrib/dynatrace-service:0.13.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: DATASTORE
              value: 'http://mongodb-datastore:8080'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: SHIPYARD_CONTROLLER
              value: 'http://shipyard-controller:8080'
            - name: PLATFORM
              value: kubernetes
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GENERATE_TAGGING_RULES
              value: 'true'
            - name: GENERATE_PROBLEM_NOTIFICATIONS
              value: 'true'
            - name: GENERATE_MANAGEMENT_ZONES
              value: 'true'
            - name: GENERATE_DASHBOARDS
              value: 'true'
            - name: GENERATE_METRIC_EVENTS
              value: 'true'
            - name: SYNCHRONIZE_DYNATRACE_SERVICES
              value: 'true'
            - name: SYNCHRONIZE_DYNATRACE_SERVICES_INTERVAL_SECONDS
              value: '300'
            - name: HTTP_SSL_VERIFY
              value: 'true'
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
        - name: distributor
          image: keptn/distributor:0.8.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-service
  labels:
    run: dynatrace-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: dynatrace-service
