---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-dynatrace-service
  labels:
    "app": "keptn"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-dynatrace-service-secrets
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-dynatrace-service-secrets
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-dynatrace-service-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-dynatrace-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-service
spec:
  selector:
    matchLabels:
      run: dynatrace-service
  replicas: 1
  template:
    metadata:
      labels:
        run: dynatrace-service
    spec:
      serviceAccountName: keptn-dynatrace-service
      containers:
        - name: dynatrace-service
          image: keptncontrib/dynatrace-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: API_WEBSOCKET_URL
              value: 'ws://api-service:8080/websocket'
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: DATASTORE
              value: 'http://mongodb-datastore:8080'
            - name: PLATFORM
              value: kubernetes
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_API_TOKEN
            - name: DT_TENANT
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_TENANT
            - name: KEPTN_API_URL
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_API_URL
            - name: KEPTN_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_API_TOKEN
            - name: KEPTN_BRIDGE_URL
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_BRIDGE_URL
                  optional: true
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GENERATE_TAGGING_RULES
              value: 'false'
            - name: GENERATE_PROBLEM_NOTIFICATIONS
              value: 'false'
            - name: GENERATE_MANAGEMENT_ZONES
              value: 'false'
            - name: GENERATE_DASHBOARDS
              value: 'false'
            - name: GENERATE_METRIC_EVENTS
              value: 'false'
            - name: SYNCHRONIZE_DYNATRACE_SERVICES
              value: 'true'
            - name: SYNCHRONIZE_DYNATRACE_SERVICES_INTERVAL_SECONDS
              value: '300'
            - name: HTTP_SSL_VERIFY
              value: 'true'
        - name: distributor
          image: keptn/distributor:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-service
  labels:
    run: dynatrace-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: dynatrace-service
