// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package credentials_mock

import (
	"github.com/keptn-contrib/dynatrace-service/internal/credentials"
	"sync"
)

// KeptnCredentialsProviderMock is a mock implementation of credentials.KeptnCredentialsProvider.
//
// 	func TestSomethingThatUsesKeptnCredentialsProvider(t *testing.T) {
//
// 		// make and configure a mocked credentials.KeptnCredentialsProvider
// 		mockedKeptnCredentialsProvider := &KeptnCredentialsProviderMock{
// 			GetKeptnCredentialsFunc: func() (*credentials.KeptnCredentials, error) {
// 				panic("mock out the GetKeptnCredentials method")
// 			},
// 		}
//
// 		// use mockedKeptnCredentialsProvider in code that requires credentials.KeptnCredentialsProvider
// 		// and then make assertions.
//
// 	}
type KeptnCredentialsProviderMock struct {
	// GetKeptnCredentialsFunc mocks the GetKeptnCredentials method.
	GetKeptnCredentialsFunc func() (*credentials.KeptnCredentials, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetKeptnCredentials holds details about calls to the GetKeptnCredentials method.
		GetKeptnCredentials []struct {
		}
	}
	lockGetKeptnCredentials sync.RWMutex
}

// GetKeptnCredentials calls GetKeptnCredentialsFunc.
func (mock *KeptnCredentialsProviderMock) GetKeptnCredentials() (*credentials.KeptnCredentials, error) {
	if mock.GetKeptnCredentialsFunc == nil {
		panic("KeptnCredentialsProviderMock.GetKeptnCredentialsFunc: method is nil but KeptnCredentialsProvider.GetKeptnCredentials was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetKeptnCredentials.Lock()
	mock.calls.GetKeptnCredentials = append(mock.calls.GetKeptnCredentials, callInfo)
	mock.lockGetKeptnCredentials.Unlock()
	return mock.GetKeptnCredentialsFunc()
}

// GetKeptnCredentialsCalls gets all the calls that were made to GetKeptnCredentials.
// Check the length with:
//     len(mockedKeptnCredentialsProvider.GetKeptnCredentialsCalls())
func (mock *KeptnCredentialsProviderMock) GetKeptnCredentialsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetKeptnCredentials.RLock()
	calls = mock.calls.GetKeptnCredentials
	mock.lockGetKeptnCredentials.RUnlock()
	return calls
}
