name: Build Helm Chart

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      version:
        type: string
        required: true
      datetime:
        type: string
        required: false
        default: ""
      release:
        description: "Set to true if the current build is for a release"
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

env:
  GO_VERSION: "^1.16"

jobs:
  helm_charts_build:
    name: Build Helm Chart
    runs-on: ubuntu-20.04
    env:
      BRANCH: ${{ inputs.branch }}
      VERSION: ${{ inputs.version }}
      DATETIME: ${{ inputs.datetime }}
      RELEASE_BUILD: ${{ inputs.release }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.2.0

      # load Image variable from .ci_env
      - name: Load CI Environment from .ci_env
        id: load_ci_env
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .ci_env

      - name: Build Helm Charts
        id: build_helm_charts
        run: |
          if [[ "$BRANCH" == "master" ]] && [[ "$RELEASE_BUILD" == 'false' ]] && [[ $DATETIME != "" ]]; then
            # use VERSION.DATETIME for the image tag (e.g., nightly build)
            ./gh-actions-scripts/build_helm_chart.sh "${VERSION}" "${VERSION}.${DATETIME}" "${IMAGE}"
          else
            # just use VERSION for the image tag
            ./gh-actions-scripts/build_helm_chart.sh "${VERSION}" "${VERSION}" "${IMAGE}"
          fi

      - name: Upload Helm Chart as an artifact
        id: upload_helm_chart
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: installer/*.tgz
