name: reviewdog
on: [ pull_request ]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.5.0
        with:
          go_version_file: "go.mod"
          tool_name: "github-pr-review"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          reviewdog_version: v0.14.2
          golangci_lint_version: v1.53.3
