
name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go
      - name: Check out code.
        uses: actions/checkout@v3
      - name: Install linters
        run: '( mkdir linters && cd linters && go get golang.org/x/lint/golint )'
      - uses: reviewdog/action-setup@v1.0.3
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review
