name: Semantic PR Validation
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
defaults:
  run:
    shell: bash
jobs:
  validate:
    uses: keptn/gh-automation/.github/workflows/validate-semantic-pr.yml@v1.4.0
    with:
      # Configure which scopes are allowed.
      scopes: |
        api
        core
        install
        deps
        deps-dev
        docs
